### ISSUE TITLE
Possible collision with ublock origin - infinite refresh

### ISSUE THREAD

**Issue by Murtadha-A** [proginosko/LeechBlockNG-chrome#28] opened 2021-02-15 13:01 UTC
The issue arose recently when I noticed the blocked tabs are being refreshed instantaneously and continuously, while the ublock origin icon is turning red and grey at the same pace (is it related? I don't know). I did have a rule to refresh blocked websites every 60 seconds (though not every millisecond, obviously!). Things were working fine until very recently. Those blocked pages will just continue to refresh endlessly until the conditions are met (a new hour comes, and they load normally). The blocked websites are facebook and twitter though I don't think it has to do with the websites themselves; Also, those tabs lost their icons sometimes, and chrome would occasionally get stuck when closed (it would close but a process would remain running, needing manual shut down before I can open it again).

**Comment by proginosko** [comment] 2021-02-15 16:52
Are you using the setting "Attempt to reload blocked page every __ seconds"?

**Comment by Murtadha-A** [comment] 2021-02-16 01:40
> Are you using the setting "Attempt to reload blocked page every __ seconds"?

Yes. Though it is set to 60 seconds.

**Comment by proginosko** [comment] 2021-02-16 01:54
Try clearing that setting and disabling uBlock, and see if the problem still arises. Process of elimination...

**Comment by Murtadha-A** [comment] 2021-02-16 16:02
> Try clearing that setting and disabling uBlock, and see if the problem still arises. Process of elimination...

I tried clearing that settings and the issue continued to occur. The website is blocked and I get the LeechBlock page instead containing the link of the blocked page, but as soon as I click that link or refresh the page it gets stuck in that endless refreshing loop.

As for ublock I now think it has nothing to do with it, since the blocked page is classified as a "chrome extension" page and ublock origin automatically ignores it (it is disabled there). The flashing of its sign is probably a result of the actual page refreshing endlessly.

**Comment by proginosko** [comment] 2021-02-17 02:38
If you can, please provide a series of steps to reproduce the problem from scratch (i.e., the settings for the block set and the URL of a page that triggers the issue). If you want to do so privately, you can email me at leechblockng@proginosko.com.

**Comment by Murtadha-A** [comment] 2021-02-20 21:53
> If you can, please provide a series of steps to reproduce the problem from scratch (i.e., the settings for the block set and the URL of a page that triggers the issue). If you want to do so privately, you can email me at [leechblockng@proginosko.com](mailto:leechblockng@proginosko.com).

Windows 10, Chrome Version 88.0.4324.182. There are tow rules only: one is to allow fb and twitter for 5mins every hour, then do the "immediate" block. The other is to block youtube between 9am and 3pm for any time exceeding a total of 20mins, but without the "immediate" block option.

The problem occur on all three sites. It is usually triggered when the link in the middle blocked page is clicked (the link of the blocked page, essentially). And sometimes the endless refresh happens without even interacting with the affected tab at all.
<img width="620" alt="desktop11" src="https://user-images.githubusercontent.com/78985176/108609480-0b958800-73c6-11eb-8e45-687fbdb64262.PNG">

**Comment by proginosko** [comment] 2021-02-20 22:46
Thanks, that's helpful. I was able to reproduce the issue. It turns out it's due to a difference in the way Chrome triggers the **webNavigation.onBeforeNavigate** event compared with Firefox. It should be a straightforward fix. Stay tuned...

**Comment by proginosko** [comment] 2021-02-21 00:46
This should be fixed in version 1.0.11.2, currently pending review.

**Closed by proginosko** 2021-02-21 00:46 UTC

**Comment by Murtadha-A** [comment] 2021-02-21 21:40
> This should be fixed in version 1.0.11.2, currently pending review.

Fixed. Cheers! :)
